//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF3._1_Millionaire.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Questions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Questions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WF3._1_Millionaire.Resources.Questions", typeof(Questions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что растёт в огороде?.
        /// </summary>
        internal static string Question001 {
            get {
                return ResourceManager.GetString("Question001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как называют микроавтобусы, совершающие поездки по определённым маршрутам?.
        /// </summary>
        internal static string Question002 {
            get {
                return ResourceManager.GetString("Question002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О чём писал Грибоедов, отмечая, что он «нам сладок и приятен» ?.
        /// </summary>
        internal static string Question003 {
            get {
                return ResourceManager.GetString("Question003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какого персонажа нет в известной считалке «На золотом крыльце сидели» ?.
        /// </summary>
        internal static string Question004 {
            get {
                return ResourceManager.GetString("Question004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой специалист занимается изучением неопознанных летающих объектов?.
        /// </summary>
        internal static string Question005 {
            get {
                return ResourceManager.GetString("Question005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как называется разновидность воды, в которой атом водорода замещён его изотопом дейтерием?.
        /// </summary>
        internal static string Question006 {
            get {
                return ResourceManager.GetString("Question006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что такое десница?.
        /// </summary>
        internal static string Question007 {
            get {
                return ResourceManager.GetString("Question007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В какое море впадает река Урал?.
        /// </summary>
        internal static string Question008 {
            get {
                return ResourceManager.GetString("Question008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На что кладут руку члены английского общества лысых во время присяги?.
        /// </summary>
        internal static string Question009 {
            get {
                return ResourceManager.GetString("Question009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как назывался каменный монолит, на котором установлен памятник Петру I в Санкт-Петербурге?.
        /// </summary>
        internal static string Question010 {
            get {
                return ResourceManager.GetString("Question010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как Пётр Ильич Чайковский назвал свою серенаду для скрипки с оркестром си-бемоль минор?.
        /// </summary>
        internal static string Question011 {
            get {
                return ResourceManager.GetString("Question011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какого ордена не было у первого советского космонавта Юрия Гагарина?.
        /// </summary>
        internal static string Question012 {
            get {
                return ResourceManager.GetString("Question012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какое животное имеет второе название — кугуар?.
        /// </summary>
        internal static string Question013 {
            get {
                return ResourceManager.GetString("Question013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что в России 19 века делали в дортуаре?.
        /// </summary>
        internal static string Question014 {
            get {
                return ResourceManager.GetString("Question014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой химический элемент назван в честь злого подземного гнома?.
        /// </summary>
        internal static string Question015 {
            get {
                return ResourceManager.GetString("Question015", resourceCulture);
            }
        }
    }
}
